appserver:
  extends:
    file: ../base/tomcat.yml
    service: appserver
  links:
    - database
  volumes:
    - ../configs/postgres.properties:/bundles/portal-ext.properties
    - ../drivers/postgresql.jar:/bundles/tomcat-7.0.62/lib/postgresql.jar
  volumes_from:
    - database
database:
  extends:
      file: ../base/postgres.yml
      service: database
