appserver:
  image: liferay/bundle-tomcat
  links:
    - database
  ports:
    - "8080:8080"
  volumes:
    - ./portal-ext.properties:/bundles/portal-ext.properties
    - ./postgresql.jar:/bundles/tomcat-7.0.62/lib/postgresql.jar
database:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=postgres
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - /bundles/data
